# Generated by Django 4.2.28 on 2026-02-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='core_commen_post_id_c20984_idx',
            old_name='core_commen_post_id_8a1f3e_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='core_commen_parent__7adc13_idx',
            old_name='core_commen_parent__9b2d4f_idx',
        ),
        migrations.RenameIndex(
            model_name='follow',
            new_name='core_follow_followe_84637a_idx',
            old_name='core_follow_followe_4c8e1b_idx',
        ),
        migrations.RenameIndex(
            model_name='follow',
            new_name='core_follow_followi_29a49d_idx',
            old_name='core_follow_followi_5d9f2c_idx',
        ),
        migrations.RenameIndex(
            model_name='like',
            new_name='core_likes_post_id_0e34ef_idx',
            old_name='core_likes_post_id_1a8b9e_idx',
        ),
        migrations.RenameIndex(
            model_name='like',
            new_name='core_likes_comment_777dcb_idx',
            old_name='core_likes_comment_3d7f2a_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='core_posts_author__2ec1d4_idx',
            old_name='core_posts_author__9a3f1c_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='core_posts_is_publ_e68b4a_idx',
            old_name='core_posts_is_publ_7d0a8b_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='core_posts_likes_c_e90725_idx',
            old_name='core_posts_likes_c_2f4e9c_idx',
        ),
        migrations.RenameIndex(
            model_name='share',
            new_name='core_shares_user_id_a410ab_idx',
            old_name='core_shares_user_id_0a0d8e_idx',
        ),
        migrations.RenameIndex(
            model_name='share',
            new_name='core_shares_post_id_b61def_idx',
            old_name='core_shares_post_id_c8f2b3_idx',
        ),
    ]
